### ISSUE TITLE
`/class add` won't work

### ISSUE THREAD

**Issue by LennyPhoenix** [Stefanuk12/HomeworkEvents#13]
![image](https://user-images.githubusercontent.com/57148878/192362350-282779ad-66db-4257-9d75-6a0952a7e1a7.png)

**Comment by LennyPhoenix** [comment]
![image](https://user-images.githubusercontent.com/57148878/192362404-5573818f-3b7b-443c-a3f5-ceb1e8c9fc4e.png)

**Comment by Stefanuk12** [comment]
i see the issue, working on a fix...

**Comment by LennyPhoenix** [comment]
Just noticed this was patched, I'll update prod tomorrow
