### ISSUE TITLE
Cache Issues with `/class remove`

### ISSUE THREAD

**Issue by LennyPhoenix** [Stefanuk12/HomeworkEvents#7]
The remove commands don't seem to actually remove the items from the cache.

**Comment by LennyPhoenix** [comment]
![image](https://user-images.githubusercontent.com/57148878/192044441-059fb7d1-3405-4562-82b0-f876c56e0b90.png)

**Comment by LennyPhoenix** [comment]
It seems like this just occurs with the Class object, not the Textbook object:
![image](https://user-images.githubusercontent.com/57148878/192046073-cec6e37b-2dad-41ab-9a83-987b0be38000.png)

**Comment by LennyPhoenix** [comment]
From the looks of it, `Textbook.remove` and `Class.remove` are very slightly different:

```ts
// Textbook.ts
const TextbookI = TextbookCache.findIndex(tb => tb.ISBN == Data.ISBN && tb.Guild == Data.Guild)
if (TextbookI == -1)
    return
```
```ts
// Class.ts
const ClassI = ClassCache.indexOf(cclass)
if (ClassI == -1)
    return
```

**Comment by LennyPhoenix** [comment]
Updating `Class.remove` to have a similar search method to `Textbook.remove` fixes this behaviour:
![image](https://user-images.githubusercontent.com/57148878/192047100-25f524b6-456b-4863-a5f9-21371716bb93.png)
Making a PR shortly.

**Comment by Stefanuk12** [comment]
Assumed this is fixed
